print("Name:Edwin Salcedo ")
print("Major:Computer Science with Cyber security Concentration")
print("Hobbies:video games and cooking")
print("Fun fact about me:I'm from state of Maryland")
print("Coolest thing I have seen about technology:Full sized phones that are foldable or AI now being incorporated into almost every product we own")
